name: Статичний аналіз та збірка

on:
  workflow_dispatch:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main
      - 'release/**'

jobs:
  build-test-analyze-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Отримання репозиторія
        uses: actions/checkout@v4

      - name: Встановлення Qt (новіша версія)
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.2'
      
      - name: Встановлення залежностей
        run: |
          sudo apt update
          sudo apt install -y libgtest-dev cppcheck

      - name: Збірка проєкту
        run: |
          cmake -B build -S src -DCMAKE_BUILD_TYPE=Release
          cmake --build build --parallel

      - name: Збереження виконуваного файлу
        uses: actions/upload-artifact@v4
        with:
          name: TaskList_Demo.x86_64
          path: build/TaskList_Demo

      - name: Запуск тестів
        run: |
          cd build
          ctest -V --output-on-failure | tee ../test-results.txt
        continue-on-error: true

      - name: Збереження результатів тестів
        uses: actions/upload-artifact@v4
        with:
          name: test-results.txt
          path: test-results.txt

      - name: Аналіз коду через SonarQube
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


  build-test-windows:
    runs-on: windows-latest
    steps:
      - name: Отримання репозиторія
        uses: actions/checkout@v4

      - name: Встановлення Qt (новіша версія)
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.2'

      - name: Встановлення залежностей
        run: |
          C:\vcpkg\vcpkg install ninja gtest

      - name: Збірка проєкту
        run: |
          cmake -B build -S src -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake
          cmake --build build --parallel

      - name: Збереження виконуваного файлу
        uses: actions/upload-artifact@v4
        with:
          name: TaskList_Demo.exe
          path: build/TaskList_Demo.exe

      - name: Запуск тестів
        shell: bash
        run: |
          cd build
          ctest -V --output-on-failure | tee ../test-results.txt
        continue-on-error: true

      - name: Збереження результатів тестів
        uses: actions/upload-artifact@v4
        with:
          name: test-results.txt
          path: test-results.txt
